---
driver:
  name: openstack
  openstack_domain_name: <%= ENV['OS_DOMAIN_NAME'] %>
  openstack_region: <%= ENV['OS_REGION_NAME'] %>
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= ENV['OS_AUTH_BASE'] %>
  openstack_project_name: <%= ENV['OS_TENANT_NAME'] %>
  network_ref: <%= ENV['OS_NETWORK_IDS'] %>
  security_groups:
  <% if ENV['OS_SECURITY_GROUPS'] %>
    <% ENV['OS_SECURITY_GROUPS'].split(',').each do |security_group| %>
      - <%= security_group %>
    <% end %>
  <% else %>
      - cloudforms_ssh_in
  <% end %>
  image_ref: <%= ENV['OS_BASE_IMAGE'] %>
  flavor_ref: <%= ENV['OS_FLAVOR_NAME'] %>
  username: <%= ENV['IMAGE_USERNAME'] %>
  key_name: <%= ENV['KEYPAIR'] %>
  floating_ip_pool: public
  allocate_floating_ip: true
  private_key_path: <%= ENV['KEYPAIR'] %>
  user_data: .kitchen_userdata.txt
<% if ENV['MODE'] == "volume" %>
  block_device_mapping:
    make_volume: true
    device_name: vdb
    volume_size: 1
    availability_zone: nova
    delete_on_termination: true
    creation_timeout: 600
<% end %>
<% if ENV['OS_NETWORK_IDS'] %> 
  network_ref: 
  <% ENV['OS_NETWORK_IDS'].split(',').each do |network| %> 
    - <%= network %> 
  <% end %> 
<% end %>

transport:
  ssh_key: <%= ENV['KEYPAIR'] %> 
  connection_timeout: 10
  connection_retries: 5
  username:  <%= ENV['IMAGE_USERNAME'] %>

provisioner:
  name: shell
<% if ENV['PROVISIONER_SCRIPT'] %>
  script: <%= ENV['PROVISIONER_SCRIPT'] %>
<% end %>

platforms:
  - name: <%= ENV['PLATFORM'] %>

suites:
  - name: <%= ENV['MODE'] %>

busser:
<% if ENV['IMAGE_USERNAME'] == "centos" %>
  ruby_bindir: "/tmp/wrap"
<% else %>
  ruby_bindir: "/usr/bin"
<% end %>
