---
driver:
  name: openstack
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
  security_groups:
  - ssh
  image_ref: <%= ENV['OS_BASE_IMAGE'] %>
  flavor_ref: m1.medium
  username: ubuntu
  key_name: <%= ENV['OS_KEY'] %>
  floating_ip_pool: nova
  private_key_path: ~/.ssh/test.pem
  block_device_mapping:
    make_volume: true
    device_name: vdb
    volume_size: 1
    availability_zone: nova
    delete_on_termination: true
    creation_timeout: 600


transport:
  ssh_key: ~/.ssh/test.pem
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu
  password: ubuntu

provisioner:
  name: shell

platforms:
  - name: ubuntu-14.04

suites:
  - name: volume

busser:
  ruby_bindir: /usr/bin