variables:
 OS_NO_CACHE: "True"
 COMPUTE_API_VERSION: "1.1"
 no_proxy: ",172.31.4.18"
 OS_CLOUDNAME: "overcloud"
 OS_AUTH_URL: "http://172.31.4.18:5000/v2.0/"
 NOVA_VERSION: "1.1"
 PACKER_BIN: "/home/gitlab-runner/packer-0.9.1"
 OS_BASE_IMAGE: "20811a86-6dbb-4ef7-9047-75a4a6727773"
 IMAGE_NAME: "ubuntu_14_04_4_WTSI_"
 OS_SECURITY_GRP: "ssh"
 OS_API_KEY: "test"
 VMWARE_BUILD_HOST: "wtgc-vmbd-01.internal.sanger.ac.uk"
 http_proxy: "http://wwwcache.sanger.ac.uk:3128"
 https_proxy: "http://wwwcache.sanger.ac.uk:3128"

stages:
 - validate
 - wordpress
 - pgsql
 - mysql
 - irods

#validate_scripts:
  # stage: init
  # tags:
  #  - shellcheck
  # allow_failure: true
  # script:
  #  - shellcheck packer.sh

validate_standard_templates:
  stage: validate
  tags: 
   - packer
  script:
   - cd ubuntu14.04
   - ./create_image.py validate -f variables.json.example 

validate_wordpress_templates:
  stage: validate
  tags: 
   - packer
  script:
   - cd ubuntu14.04-wordpress
   - ./create_image.py validate 

validate_mysql_templates:
  stage: validate
  tags: 
   - packer
  script:
   - cd ubuntu14.04-mysql
   - ./create_image.py validate 

validate_pgsql_templates:
  stage: validate
  tags: 
   - packer
  script:
   - cd ubuntu14.04-pgsql
   - ./create_image.py validate 

validate_iRODS_templates:
  stage: validate
  tags: 
   - packer
  script:
   - cd ubuntu14.04-iRODS
   - ./create_image.py validate 

build_openstack_wordpress:
 stage: wordpress
 tags:
  - packer
 script:
  - cd ubuntu14.04-wordpress
  - IMAGE_NAME=${IMAGE_NAME}"wordpress_"
  - ./create_image.py build -p openstack -o $IMAGE_NAME -s 

build_vmware_wordpress:
  stage: wordpress
  tags:
   - packer
  script:
   - cd ubuntu14.04-wordpress
   - sshpass -p $VMWARE_PASSWORD scp -oStrictHostKeyChecking=no  vmbuildadmin@wtgc-vmbd-01.internal.sanger.ac.uk:~/vmware_private_key.pem .
   - IMAGE_NAME=${IMAGE_NAME}"wordpress_"$(date +%Y%m%d%H%M%S )
   - ./create_image.py build -p vmware-iso -o $IMAGE_NAME

build_openstack_mysql:
 stage: mysql
 tags:
  - packer
 script:
  - cd ubuntu14.04-mysql
  - IMAGE_NAME=${IMAGE_NAME}"mysql_"
  - ./create_image.py build -p openstack -o $IMAGE_NAME -s 

build_vmware_mysql:
  stage: mysql
  tags:
   - packer
  script:
   - cd ubuntu14.04-mysql
   - sshpass -p $VMWARE_PASSWORD scp -oStrictHostKeyChecking=no  vmbuildadmin@wtgc-vmbd-01.internal.sanger.ac.uk:~/vmware_private_key.pem .
   - IMAGE_NAME=${IMAGE_NAME}"mysql_"$(date +%Y%m%d%H%M%S )
   - ./create_image.py build -p vmware-iso -o $IMAGE_NAME

build_openstack_pgsql:
 stage: pgsql
 tags:
  - packer
 script:
  - cd ubuntu14.04-pgsql
  - IMAGE_NAME=${IMAGE_NAME}"pgsql_"
  - ./create_image.py build -p openstack -o $IMAGE_NAME -s 

build_vmware_pgsql:
  stage: pgsql
  tags:
   - packer
  script:
   - cd ubuntu14.04-pgsql
   - sshpass -p $VMWARE_PASSWORD scp -oStrictHostKeyChecking=no  vmbuildadmin@wtgc-vmbd-01.internal.sanger.ac.uk:~/vmware_private_key.pem .
   - IMAGE_NAME=${IMAGE_NAME}"pgsql_"$(date +%Y%m%d%H%M%S )
   - ./create_image.py build -p vmware-iso -o $IMAGE_NAME


build_openstack_irods:
 stage: irods
 tags:
  - packer
 script:
  - LATEST=514
  - cd ubuntu14.04-iRODS
  - scp -oStrictHostKeyChecking=no gitlab-runner@172.17.27.70:/opt/packages/ubuntu1404/irods/"$LATEST"/irods-icat-4.1.8-64bit.deb ./files
  - scp -oStrictHostKeyChecking=no gitlab-runner@172.17.27.70:/opt/packages/ubuntu1404/irods/"$LATEST"/irods-database-plugin-postgres-1.8.deb ./files
  - IMAGE_NAME=${IMAGE_NAME}"iRODS_"
  - ./create_image.py build -p openstack -o $IMAGE_NAME -s 

build_vmware_irods:
  stage: irods
  tags:
   - packer
  script:
   - LATEST=514
   - cd ubuntu14.04-iRODS
   - scp -oStrictHostKeyChecking=no gitlab-runner@172.17.27.70:/opt/packages/ubuntu1404/irods/"$LATEST"/irods-icat-4.1.8-64bit.deb ./files
   - scp -oStrictHostKeyChecking=no gitlab-runner@172.17.27.70:/opt/packages/ubuntu1404/irods/"$LATEST"/irods-database-plugin-postgres-1.8.deb ./files
   - sshpass -p $VMWARE_PASSWORD scp -oStrictHostKeyChecking=no  vmbuildadmin@wtgc-vmbd-01.internal.sanger.ac.uk:~/vmware_private_key.pem .
   - IMAGE_NAME=${IMAGE_NAME}"iRODS_"$(date +%Y%m%d%H%M%S )
   - ./create_image.py build -p vmware-iso -o $IMAGE_NAME




# test_openstack_irods:
#   stage: test 
#   tags:
#   - kitchen 
#   script:
#   - echo $USER
#   - echo $PWD
#   - old_proxy=http://wwwcache.sanger.ac.uk:3128
#   - unset http_proxy
#   - unset https_proxy
#   - kitchen verify
#   - export http_proxy=$old_proxy
#   - export https_proxy=$old_proxy



# build_virtualbox_irods:
#  stage: build
#  tags:
#   - packer
#  script:
#   - LATEST=514
#   - scp -oStrictHostKeyChecking=no gitlab-runner@172.17.27.70:/opt/packages/ubuntu1404/irods/"$LATEST"/irods-icat-4.1.8-64bit.deb ./files
#   - scp -oStrictHostKeyChecking=no gitlab-runner@172.17.27.70:/opt/packages/ubuntu1404/irods/"$LATEST"/irods-database-plugin-postgres-1.8.deb ./files
#   - ./packer.sh build virtualbox
