---
driver:
  name: openstack
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
  security_groups:
  - ssh
  image_ref: <%= ENV['OS_BASE_IMAGE'] %>
  flavor_ref: m1.medium
  username: <%= ENV['IMAGE_USERNAME'] %>
  key_name: <%= ENV['KEYPAIR'] %>
  floating_ip_pool: nova
  private_key_path: <%= ENV['KEYPAIR'] %>
<% if ENV['MODE'] == "volume" %>
  block_device_mapping:
    make_volume: true
    device_name: vdb
    volume_size: 1
    availability_zone: nova
    delete_on_termination: true
    creation_timeout: 600
<% end %>


transport:
  ssh_key: <%= ENV['KEYPAIR'] %> 
  connection_timeout: 10
  connection_retries: 5
  username:  <%= ENV['IMAGE_USERNAME'] %>

provisioner:
  name: shell

platforms:
  - name: <%= ENV['PLATFORM'] %>

suites:
  - name: <%= ENV['MODE'] %>

busser:
  ruby_bindir: /usr/bin
